export type IconType = Record<Package, unknown> & {
  basic: BasicIcon;
  finance: FinanceIcon;
  file: FileIcon;
  switch: SwitchIcon;
  gadget: GadgetIcon;
  media: MediaIcon;
  alert: AlertIcon;
  tool: ToolIcon;
  arrow: ArrowIcon;
  security: SecurityIcon;
  time: TimeIcon;
  map: MapIcon;
  currency: CurrencyIcon;
  flag: FlagIcon;
  logo: LogoIcon;
  other: OtherIcon;
  emotion: EmotionIcon;
  crypto: CryptoIcon;
  social: SocialIcon;
};

export type Package = keyof typeof PackageEnum;
export type BasicIcon = keyof typeof BasicIconEnum;
export type FileIcon = keyof typeof FileIconEnum;
export type SwitchIcon = keyof typeof SwitchIconEnum;
export type FinanceIcon = keyof typeof FinanceIconEnum;
export type GadgetIcon = keyof typeof GadgetIconEnum;
export type MediaIcon = keyof typeof MediaIconEnum;
export type AlertIcon = keyof typeof AlertIconEnum;
export type ToolIcon = keyof typeof ToolIconEnum;
export type ArrowIcon = keyof typeof ArrowIconEnum;
export type SecurityIcon = keyof typeof SecurityIconEnum;
export type TimeIcon = keyof typeof TimeIconEnum;
export type MapIcon = keyof typeof MapIconEnum;
export type CurrencyIcon = keyof typeof CurrencyIconEnum;
export type FlagIcon = keyof typeof FlagIconEnum;
export type LogoIcon = keyof typeof LogoIconEnum;
export type OtherIcon = keyof typeof OtherIconEnum;
export type EmotionIcon = keyof typeof EmotionIconEnum;
export type CryptoIcon = keyof typeof CryptoIconEnum;
export type SocialIcon = keyof typeof SocialIconEnum;

// Use object for checking key duplication and collapsable in code editor
// Not use Enum b/c enum key is not support `number` in case `media/360`

export const PackageEnum = {
  basic: 'basic',
  finance: 'finance',
  file: 'file',
  switch: 'switch',
  gadget: 'gadget',
  media: 'media',
  alert: 'alert',
  tool: 'tool',
  emotions: 'emotions',
  crypto: 'crypto',
  arrow: 'arrow',
  security: 'security',
  time: 'time',
  map: 'map',
  currency: 'currency',
  flag: 'flag',
  logo: 'logo',
  other: 'other',
  social: 'social',
};
export const BasicIconEnum = {
  empty: 'empty',
  setting: 'setting',
  solid_square_setting: 'solid_square_setting',
  setting_account: 'setting_account',
  eye_open: 'eye_open',
  eye_closed: 'eye_closed',
  trash_bin: 'trash_bin',
  download: 'download',
  upload: 'upload',
  globe: 'globe',
  zoom: 'zoom',
  rocket: 'rocket',
  voucher: 'voucher',
  person: 'person',
  no_person: 'no_person',
  person_add: 'person_add',
  person_remove: 'person_remove',
  persons: 'persons',
  group_add: 'group_add',
  group_remove: 'group_remove',
  supervisor_person: 'supervisor_person',
  person_voice: 'person_voice',
  solid_circle_person: 'solid_circle_person',
  solid_square_person: 'solid_square_person',
  mail: 'mail',
  mail_attach: 'mail_attach',
  heart: 'heart',
  heart_border: 'heart_border',
  star: 'star',
  half_star: 'half_star',
  star_border: 'star_border',
  solid_circle_star: 'solid_circle_star',
  thumb_up: 'thumb_up',
  thumb_down: 'thumb_down',
  thumbs_up_down: 'thumbs_up_down',
  edit: 'edit',
  edit_hide: 'edit_hide',
  rename: 'rename',
  reward: 'reward',
  bolt: 'bolt',

  translate: 'translate',
  solid_circle_more: 'solid_circle_more',
  close: 'close',
  solid_circle_close: 'solid_circle_close',
  minus: 'minus',
  solid_circle_minus: 'solid_circle_minus',
  plus: 'plus',
  solid_circle_plus: 'solid_circle_plus',
  copy: 'copy',
  news: 'news',
  list_checked: 'list_checked',
  chat_bubble: 'chat_bubble',
  send: 'send',
  attach_file: 'attach_file',
  link: 'link',
  link_hide: 'link_hide',
  add_link: 'add_link',
  qr_code: 'qr_code',
  qr_code_scanner: 'qr_code_scanner',
  scanner: 'scanner',
  fingerprint: 'fingerprint',
  scan_fingerprint: 'scan_fingerprint',
  scan_face_id: 'scan_face_id',
  question: 'question',
  address_book: 'address_book',
  building: 'building',
  scroll: 'scroll',
  more: 'more',
  checked: 'checked',
  double_checked: 'double_checked',
  double_checked_hide: 'double_checked_hide',
  dot: 'dot',
  share: 'share',
  ios_share: 'ios_share',
  filter: 'filter',
  search: 'search',
  launch: 'launch',
  sign_in: 'sign_in',
  sign_out: 'sign_out',
  list_open: 'list_open',
  list_verified: 'list_verified',
  list_add: 'list_add',
  burger_menu: 'burger_menu',
  list: 'list',
  menu: 'menu',
};
export const FinanceIconEnum = {
  wallet: 'wallet',
  wallet_plus: 'wallet_plus',
  wallet_minus: 'wallet_minus',
  saving: 'saving',
  bank: 'bank',
  receipt: 'receipt',

  bank_note: 'bank_note',
  solid_circle_dollar: 'solid_circle_dollar',
  earn: 'earn',
  credit_card_face: 'credit_card_face',
  credit_card: 'credit_card',
  credit_card_hide: 'credit_card_hide',
  payments: 'payments',
  withdraw: 'withdraw',
  cash_in: 'cash_in',
  candle_fill: 'candle_fill',
  trade: 'trade',
  line_chart_fill: 'line_chart_fill',
  line_chart_stroke: 'line_chart_stroke',
  exchange_dollar_line: 'exchange_dollar_line',
};

export const FileIconEnum = {
  folder: 'folder',
  add_folder: 'add_folder',
  folder_send: 'folder_send',
  folder_upload: 'folder_upload',
  folder_download: 'folder_download',

  document: 'document',
  document_add: 'document_add',
  document_send: 'document_send',
  document_upload: 'document_upload',
  document_download: 'document_download',
  document_profile: 'document_profile',
  document_search: 'document_search',
  document_attach: 'document_attach',
};

export const SwitchIconEnum = {
  check_box_default: 'check_box_default',
  check_box_disable: 'check_box_disable',
  check_box_checked_disable: 'check_box_checked_disable',
  check_box_checked: 'check_box_checked',
  check_box_indeterminate: 'check_box_indeterminate',

  radio_button_checked_disable: 'radio_button_checked_disable',
  radio_button_checked: 'radio_button_checked',
  radio_button_selected_disable: 'radio_button_selected_disable',
  radio_button_selected: 'radio_button_selected',
  radio_button_disable: 'radio_button_disable',
  radio_button_default: 'radio_button_default',

  checked: 'checked',

  toggle_on_disable: 'toggle_on_disable',
  toggle_on: 'toggle_on',
  toggle_off_disable: 'toggle_off_disable',
  toggle_off: 'toggle_off',
};

export const GadgetIconEnum = {
  laptop: 'laptop',
  iphone_1: 'iphone_1',
  android_phone_2: 'android_phone_2',
  android_tablet: 'android_tablet',
  ipad: 'ipad',
  server: 'server',
  moniter: 'moniter',
  usb: 'usb',
  memory_card: 'memory_card',
  sim: 'sim',
  headset_mic: 'headset_mic',
  keyboard: 'keyboard',
};

export const MediaIconEnum = {
  flassh_on: 'flassh_on',
  flassh_off: 'flassh_off',
  '360': '360',
  hdr_off: 'hdr_off',
  hdr_on: 'hdr_on',
  flash_auto: 'flash_auto',
  flip_camera: 'flip_camera',
  camera: 'camera',
  filming_add: 'filming_add',
  filming: 'filming',
  filming_hide: 'filming_hide',
  multi_image: 'multi_image',
  image: 'image',
  mic_on: 'mic_on',
  mic_off: 'mic_off',
  multi_video: 'multi_video',
  player_play: 'player_play',
  player_pause: 'player_pause',
  player_fast_rewind: 'player_fast_rewind',
  player_fast_forward: 'player_fast_forward',
  player_skip_previous: 'player_skip_previous',
  player_skip_next: 'player_skip_next',
  player_replay: 'player_replay',
  player_repeat: 'player_repeat',
};

export const AlertIconEnum = {
  quote: 'quote',
  announce: 'announce',
  announce_2: 'announce_2',
  warning: 'warning',
  error: 'error',
  help: 'help',
  information: 'information',
  notice: 'notice',
  success: 'success',
  notification_edit: 'notification_edit',
  notification_active: 'notification_active',
  notification_hide: 'notification_hide',
  notification: 'notification',
  notification_warning: 'notification_warning',
  notification_snooze: 'notification_snooze',
  notification_add: 'notification_add',
  solid_circle_notification: 'solid_circle_notification',
  notification_outlined: 'notification_outlined',
  notification_filled: 'notification_filled',
};

export const ToolIconEnum = {
  calculator: 'calculator',
};

export const ArrowIconEnum = {
  solid_circle_arrow_right: 'solid_circle_arrow_right',
  sort: 'sort',
  solid_circle_direction_left: 'solid_circle_direction_left',
  solid_circle_direction_downward: 'solid_circle_direction_downward',
  solid_circle_direction_right: 'solid_circle_direction_right',
  solid_circle_direction_upward: 'solid_circle_direction_upward',
  solid_circle_refresh_ccw: 'solid_circle_refresh_ccw',
  solid_circle_arrow_bottom_left: 'solid_circle_arrow_bottom_left',
  solid_circle_rotate_ccw: 'solid_circle_rotate_ccw',
  solid_circle_rotate_cw: 'solid_circle_rotate_cw',
  solid_circle_arrow_bottom_right: 'solid_circle_arrow_bottom_right',
  chevrons_left: 'chevrons_left',
  chevron_left: 'chevron_left',
  solid_circle_arrow_top_right: 'solid_circle_arrow_top_right',
  chevron_right: 'chevron_right',
  chevrons_downward: 'chevrons_downward',
  chevron_upward: 'chevron_upward',
  circle_arrow_upward: 'circle_arrow_upward',
  chevrons_right: 'chevrons_right',
  circle_arrow_top_left: 'circle_arrow_top_left',
  circle_arrow_downward: 'circle_arrow_downward',
  circle_arrow_bottom_left: 'circle_arrow_bottom_left',
  circle_arrow_bottom_right: 'circle_arrow_bottom_right',
  circle_arrow_top_right: 'circle_arrow_top_right',
  circle_arrow_right: 'circle_arrow_right',
  direction_up: 'direction_up',
  direction_right: 'direction_right',
  circle_arrow_left: 'circle_arrow_left',
  direction_down: 'direction_down',
  direction_left: 'direction_left',
  solid_left: 'solid_left',
  solid_right: 'solid_right',
  solid_upward: 'solid_upward',
  solid_circle_arrow_downward: 'solid_circle_arrow_downward',
  solid_downward: 'solid_downward',
  solid_circle_arrow_upward: 'solid_circle_arrow_upward',
  solid_circle_arrow_left: 'solid_circle_arrow_left',
  solid_circle_arrow_top_left: 'solid_circle_arrow_top_left',
  arrow_top_left: 'arrow_top_left',
  unfold_more: 'unfold_more',
  unfold_less: 'unfold_less',
  solid_cirle_left: 'solid_cirle_left',
  solid_cirle_right: 'solid_cirle_right',
  solid_cirle_drop_downward: 'solid_cirle_drop_downward',
  arrow_forward: 'arrow_forward',
  arrow_back: 'arrow_back',
  arrow_downward: 'arrow_downward',
  arrow_upward: 'arrow_upward',
  rotate_cw: 'rotate_cw',
  rotate_ccw: 'rotate_ccw',
  refresh_cw: 'refresh_cw',
  arrow_top_right: 'arrow_top_right',
  arrow_bottom_left: 'arrow_bottom_left',
  arrow_bottom_right: 'arrow_bottom_right',
  refresh_cw_alert: 'refresh_cw_alert',
  refresh_ccw: 'refresh_ccw',
  chevron_downward: 'chevron_downward',
  solid_cirle_drop_upward: 'solid_cirle_drop_upward',
  refresh_ccw_alert: 'refresh_ccw_alert',
  forward: 'forward',
  backward: 'backward',
  solid_circle_swap_horizontal: 'solid_circle_swap_horizontal',
  undo: 'undo',
  redo: 'redo',
  exchange_highlight: 'exchange_highlight',
  exchange: 'exchange',
  solid_circle_swap_vertical: 'solid_circle_swap_vertical',
  swap_vert: 'swap_vert',
  compare: 'compare',
  swap_horiz: 'swap_horiz',
  switch: 'switch',
  arrow_drop_down: 'arrow_drop_down',
  arrow_right_alt: 'arrow_right_alt',
};

export const SecurityIconEnum = {
  key: 'key',
  key_hide: 'key_hide',
  lock_clock: 'lock_clock',
  lock_open: 'lock_open',
  lock: 'lock',
  lock_hide: 'lock_hide',
  shield: 'shield',
  shield_warning: 'shield_warning',
  shield_lock: 'shield_lock',
  shield_hide: 'shield_hide',
  shield_star: 'shield_star',
  shield_plus: 'shield_plus',
  shield_account: 'shield_account',
  lock_plus: 'lock_plus',
  shield_check: 'shield_check',
};

export const TimeIconEnum = {
  calendar_busy: 'calendar_busy',
  calendar_available: 'calendar_available',
  calendar_event: 'calendar_event',
  calendar: 'calendar',
  solid_calendar: 'solid_calendar',
  solid_calendar_event: 'solid_calendar_event',
  solid_calendar_date_range: 'solid_calendar_date_range',
  solid_calendar_busy: 'solid_calendar_busy',
  solid_calendar_available: 'solid_calendar_available',
  calendar_date_range: 'calendar_date_range',
  clock_cw_update: 'clock_cw_update',
  clock_ccw_history: 'clock_ccw_history',
  solid_circle_clock: 'solid_circle_clock',
  clock: 'clock',
};

export const MapIconEnum = {
  explore_off: 'explore_off',
  explore: 'explore',
  gps_off: 'gps_off',
  map: 'map',
  location_edit: 'location_edit',
  location_warning: 'location_warning',
  personal_location: 'personal_location',
  gps: 'gps',
  location: 'location',
};

export const CurrencyIconEnum = {
  sgd: 'sgd',
  vnd: 'vnd',
  usd: 'usd',
  visacard: 'visacard',
  mastercard: 'mastercard',
  grabpay: 'grabpay',
};

export const FlagIconEnum = {
  english: 'english',
  us: 'us',
  singapore: 'singapore',
  vietnam: 'vietnam',
};

export const LogoIconEnum = {
  facebook: 'facebook',
  telegram: 'telegram',
  twitter: 'twitter',
  linkedin: 'linkedin',
  angellist: 'angellist',
  instagram: 'instagram',
  reddit: 'reddit',
  metamask: 'metamask',
  walletconnect: 'walletconnect',

  visa: 'visa',
  mastercard: 'mastercard',
  grabpay: 'grabpay',
};

export const OtherIconEnum = {
  loading: 'loading',
  point: 'point',
};

export const EmotionIconEnum = {
  19: '19',
  20: '20',
  21: '21',
  9: '9',
  10: '10',
  11: '11',
  12: '12',
  13: '13',
  14: '14',
  15: '15',
  17: '17',
  16: '16',
  8: '8',
  7: '7',
  6: '6',
  5: '5',
  4: '4',
  3: '3',
  18: '18',
  22: '22',
  23: '23',
  24: '24',
  25: '25',
  26: '26',
  27: '27',
  28: '28',
  29: '29',
  30: '30',
  2: '2',
  1: '1',
};

export const CryptoIconEnum = {
  grt: 'grt',
  fil: 'fil',
  crv: 'crv',
  doge: 'doge',
  enj: 'enj',
  doge2: 'doge2',
  pax: 'pax',
  idk: 'idk',
  neo: 'neo',
  zec: 'zec',
  dai: 'dai',
  mco: 'mco',
  gto: 'gto',
  bnb: 'bnb',
  xrp: 'xrp',
  ada: 'ada',
  mkr: 'mkr',
  bat: 'bat',
  gnt: 'gnt',
  knc: 'knc',
  dat: 'dat',
  usdt: 'usdt',
  tusd: 'tusd',
  zil: 'zil',
  eos: 'eos',
  ksm: 'ksm',
  band: 'band',
  comp: 'comp',
  one: 'one',
  idrt: 'idrt',
  uni: 'uni',
  snx: 'snx',
  link: 'link',
  algo: 'algo',
  xmr: 'xmr',
  atom: 'atom',
  srm: 'srm',
  ftt: 'ftt',
  matic: 'matic',
  '1inch': '1inch',
  sand: 'sand',
  vet: 'vet',
  icp: 'icp',
  rune: 'rune',
  xtz: 'xtz',
  aave: 'aave',
  mith: 'mith',
  theta: 'theta',
  snt: 'snt',
  omg: 'omg',
  snm: 'snm',
  storm: 'storm',
  wtc: 'wtc',
  libra: 'libra',
  zrx: 'zrx',
  luna: 'luna',
  sushi: 'sushi',
  hbar: 'hbar',
  eth: 'eth',
  bch: 'bch',
  btc: 'btc',
  ltc: 'ltc',
  sol: 'sol',
  mana: 'mana',
  dgd: 'dgd',
  usdc: 'usdc',
  xlm: 'xlm',
  cvc: 'cvc',
  grin: 'grin',
  dot: 'dot',
  avax: 'avax',
  dydx: 'dydx',
  qnt: 'qnt',
  klay: 'klay',
  flow: 'flow',
  shib: 'shib',
  xyz: 'xyz',
  mx: 'mx',
  ens: 'ens',
  imx: 'imx',
  ust: 'ust',
  yfi: 'yfi',
  btt: 'btt',
  egld: 'egld',
  sc: 'sc',
  iota: 'iota',
  ftm: 'ftm',
  near: 'near',
  alice: 'alice',
  axs: 'axs',
  gala: 'gala',
  lrc: 'lrc',
  cel: 'cel',
  chz: 'chz',
  nano: 'nano',
  clv: 'clv',
};

export const SocialIconEnum = {
  facebook: 'facebook',
  twitter: 'twitter',
  linkedin: 'linkedin',
  instagram: 'instagram',
};
