image: node:latest
stages:
  - build
  - deploy
# - test

variables:
  LC_ALL: 'en_US.UTF-8'
  LANG: 'en_US.UTF-8'
  GIT_STRATEGY: clone
  API_URL: 'https://b2b.abc.com'
  PRODUCTION: 1
  MESSAGE_ANDROID: "[*Interior Design Mobile*]\n*API_URL*: $API_URL\n*Android* has been built successfully: \"$CI_COMMIT_MESSAGE\" Hey <users/104121422729815117160>! Click to download *APK* file http://192.168.9.62/loa/loa-mobile/-/jobs/$CI_JOB_ID/artifacts/download"
  MESSAGE_IOS: "[*Interior Design Mobile*]\n*API_URL*: $API_URL\n*iOS* has been built & upload to *TestFlight* successfully: \"$CI_COMMIT_MESSAGE\" Hey <users/104121422729815117160>! Please update & help me test it."

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

#########################
###### Build Stage ######
#########################
build:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build:prod
  only:
    - develop
    - master
  tags:
    - ios
  artifacts:
    paths:
      - www
    expire_in: 2 hrs

#########################
###### Test Stage ######
#########################

test:
  stage: test
  script:
    - npm run test:ci
  tags:
    - ios
  variables:
    GIT_STRATEGY: none
  artifacts:
    paths:
      - coverage
    expire_in: 1 month

#########################
###### Deploy Stage ######
#########################

upload_to_testflight:
  stage: deploy
  script:
    - echo "----------------------------------------------------------------"
    - echo "Upload to TestFlight by " $FASTLANE_USER
    - npm run sync -- ios
    - npm run deploy:ios
  variables:
    GIT_STRATEGY: none
  retry: 2
  only:
    - develop
    - master
  tags:
    - ios

build_apk:
  stage: deploy
  script:
    - echo "----------------------------------------------------------------"
    - echo "Build Android app to APK by " $FASTLANE_USER
    - npm run sync -- android
    - npm run deploy:android
    - cp android/app/build/outputs/apk/debug/app-debug.apk $PWD/loa.apk
  variables:
    GIT_STRATEGY: none
  only:
    - develop
    - master
  tags:
    - ios
  artifacts:
    paths:
      - loa.apk
    expire_in: 1 week
