version: '3'
services:

  next:
    container_name: next
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ${NODE_ENV}
    env_file: .env

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=newuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=eduviet
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
    ports:
      - 5050:80
    depends_on:
      - db
volumes:
  db-data:
