image: node:latest
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@7.1.2
    - npm install
    - npm run build-gitlab
  artifacts:
    paths:
      - public
  only:
    - master
    - develop
    - pages